### ISSUE TITLE
Deploy Using GITHUB page

### ISSUE THREAD

**Issue by shuja-shah** [shuja-shah/Personal-Portfolio-MOBILE-SKELETON#6]
### Deployment using the GitHub page to demonstrate personal portfolio.

- Used a custom Domain by creating a new branch as showcased in w3schools.
-  Enforced HTTPs at the page.
-  Updated the readme.MD to include a link in the live demo section.

https://shuja-shah.github.io/

**Comment by zhadier** [comment]
## Hi @shuja-shah  👋  

Your project is complete!  Great job on the deployment 🔥 

# Congratulations! 🎉 

### Keep Rocking!👏👏👏


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
